server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic1: "order-topic"
    kafkaMessageTopic2: "order-status-topic"
    kafkaMessageGroupId: "order-status-group"