server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:91.197.98.213:9094}
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=schema_account
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 100000

  liquibase:
    drop-first: true

#eureka:
#  client:
#    enabled: false
