server:
  port: 8082
spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
#  redis:
#    host: 8082
#    port: 6379
#    cacheType: redis
#    cashe-names:
#      - books
#      - booksByCategory
