server:
  port: 0
spring:
  application:
    name: account-service
#  profiles:
#    active: test

  main:
    allow-circular-references: true
  jpa:
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
##    url: jdbc:postgresql://postgres:5432/account_db?currentSchema=schema_account
    url: jdbc:postgresql://91.197.98.213:5432/account_db?currentSchema=schema_account
    username: postgre_user
    password: postgre_secret_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 100000
  liquibase:
    change_log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:91.197.98.213:9094}

  cloud:
    config:
      import-check:
        enabled: false
      discovery:
        enabled: true
        service-id: config-service
      fail-fast: true

logging:
  level:
#   org.springframework: DEBUG
   com.example: TRACE
#   com.zaxxer.hikari.*: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://91.197.98.213:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true


#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

app:
  kafka:
    topic:
      registration: "registration-topic"
      createdAccount: "created-account-topic"
      deletedAccount: "deleted-account-topic"
      blockedAccount: "blocked-account-topic"
      unblockedAccount: "unblocked-account-topic"
      accountBirthDay: "account.birthdate"
      userIsOnline: "user-is-online-topic"
      changedEmail: "changed-email-topic"
    kafkaMessageGroupId: "kafka-account-group-id"

gateway:
  api:
    url: ${GATEWAY_URL:http://91.197.98.213:8080}