#server:
#  port: 8082
spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels_db
    username: postgres
    password: postgres
    hikari:
      schema: hotels_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotels_schema
      connection-timeout: 10000
